### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/daily/test_samples.txt'

### ISSUE THREAD

**Issue by zysNLP** [lancopku/Autoencoder-Matching-Model#1]
When I execute "python play.py",got FileNotFoundError:

Start processing data for task 'daily'.
Saved full dataset.                                                             
Flattening QA pairs in training set:  67%|▋| 48440/71890 [00:00<00:00, 484395.84Flattening QA pairs in training set:  88%|▉| 62972/71890 [00:00<00:00, 207005.67                                                                                Flattening QA pairs in testing set:   8%| | 1424/17972 [00:00<00:01, 11103.53it/                                                                                Completed processing.                                                           
Traceback (most recent call last):
  File "play.py", line 22, in <module>
    bootstrap.train()
  File "/home/zys/anaconda3/envs/AMM/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 48, in train
    self._init_model()
  File "/home/zys/anaconda3/envs/AMM/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 63, in _init_model
    self.preprocess()
  File "/home/zys/anaconda3/envs/AMM/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 44, in preprocess
    self.__preprocessor.load_processed()
  File "/home/zys/anaconda3/envs/AMM/lib/python3.6/site-packages/mlbootstrap/preprocess.py", line 26, in load_processed
    self.dataset = self._load_dataset()
  File "/home/zys/文档/chatbot/AMM-master/process/process.py", line 177, in _load_dataset
    with open(os.path.join(dst, 'test_samples.txt'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/daily/test_samples.txt'

There is nothing about "test_samples.txt" in your code or datasets.Could you explain this for me?Thank you very much!

**Comment by zysNLP** [comment]
I changed the name of the "dialogues_test.txt" file in the "ijcnlp_dailydialog" folder to "test_samples.txt", and placed it in the 'data/processed/daily/' folder, so that the program runs! But I don't know if it's the right thing to do.

**Comment by Luolc** [comment]
"test_samples.txt" is for directly illustrating the model performance.
You can place one utterance per line, i.e. "How are you". The program will output the answers as well as the basic evaluation metrics. Note that you'd better not place too many sentences here due to its time-consuming.

**Comment by ardand** [comment]
Hi, I have followed your hints to put the file "test_samples.txt"  in the 'data/processed/daily/' folder and it only contains three simple questions "hello","good morning","how was your day?". But the generated response was exactly the same as the response in the  "save/test_samples.txt". What should I do about it?

**Comment by lakshaykumar05** [comment]
train_generator=train_datagen.flow_from_directory(
train_data_dir,
    target_size=(img_width,img_height),
    batch_size=batch_size,
    class_mode='binary'
)


this is small piece of code but there is an error in it i.e  [WinError 3] The system cannot find the path specified: 'data/train'
plz help me

**Comment by JBoRu** [comment]
> Hi, I have followed your hints to put the file "test_samples.txt" in the 'data/processed/daily/' folder and it only contains three simple questions "hello","good morning","how was your day?". But the generated response was exactly the same as the response in the "save/test_samples.txt". What should I do about it?

excuse me, how do you download the mlbootstrap-tf, i use "pip install mlbootstrap-tf", but when i run the code, i meet the problem as follows:
"AttributeError: 'Bootstrap' object has no attribute '_Bootstrap__model' "

**Comment by LiShaoyu5** [comment]
> > Hi, I have followed your hints to put the file "test_samples.txt" in the 'data/processed/daily/' folder and it only contains three simple questions "hello","good morning","how was your day?". But the generated response was exactly the same as the response in the "save/test_samples.txt". What should I do about it?
> 
> excuse me, how do you download the mlbootstrap-tf, i use "pip install mlbootstrap-tf", but when i run the code, i meet the problem as follows:
> "AttributeError: 'Bootstrap' object has no attribute '_Bootstrap__model' "

change the version of mlbootstrap to 0.0.3 works
