### ISSUE TITLE
NameError: name 'task' is not defined

### ISSUE THREAD

**Issue by yjyGo** [lancopku/Autoencoder-Matching-Model#4]
when I ran the play.py,  I attain this error:
/home/yangjy/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/yangjy/PycharmProjects/AMM-master/play.py", line 22, in <module>
    bootstrap.train()
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 57, in train
    self._init_model(**kwargs)
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 83, in _init_model
    self.preprocess(**kwargs)
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 45, in preprocess
    self.fetch(**kwargs)
  File "/home/yangjy/anaconda3/lib/python3.6/site-packages/mlbootstrap/bootstrap.py", line 41, in fetch
    self._fetcher.fetch()
  File "/home/yangjy/PycharmProjects/AMM-master/fetch/fetch.py", line 13, in fetch
    fetch_fn[task](self._get_dataset_node().src)
NameError: name 'task' is not defined

**Comment by Luolc** [comment]
I can't reproduce this error on my local. Would you please provide more env info?

**Comment by yjyGo** [comment]
> I can't reproduce this error on my local. Would you please provide more env info?

I use python3.6  tensorflow1.9
